
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
