
spring:
  rabbitmq:
    host: rabbitmq-bus
    port: 5672
    username: rabbitmq
    password: rabbitmq


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
#  instance:
#    prefer-ip-address: true
#    hostname: ${server.address}
#    ip-address: ${server.address}

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000