
spring:
  rabbitmq:
    host: rabbitmq-bus
    port: 5672
    username: rabbitmq
    password: rabbitmq


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    registry-fetch-interval-seconds: 5

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000