
spring:
  rabbitmq:
    host: rabbitmq-bus
    port: 5672
    username: rabbitmq
    password: rabbitmq


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
