spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://catalogdb:3306/items
    username: root
    password: dbpass
    initialize: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/{vendor},classpath:db/migration/common
