spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://catalogdb:5432/items
    username: items
    password: items
    initialize: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/{vendor},classpath:db/migration/common
