spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://customerdb:5432/customer
    username: customer
    password: customer
    initialize: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  flyway:
    locations: classpath:db/migration/{vendor},classpath:db/migration/common
