spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://orderdb:5432/order
    username: order
    password: order
    initialize: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/{vendor},classpath:db/migration/common
order:
  discount: 0.0
  customerServiceUrl: http://customersvc:8080/customers/
  catalogServiceUrl: http://catalogsvc:8080/items/